routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('items/index');
});

Route::get('/data-tables', function () {
    return view('items/data-tables');
});

// Route::get('/pertanyaan/create', 'pertanyaanController@create');
// Route::post('/pertanyaan', 'pertanyaanController@store');
// Route::get('/pertanyaan', 'pertanyaanController@index')->name('pertanyaan.index');
// Route::get('/pertanyaan/{pertanyaan_id}', 'pertanyaanController@show');
// Route::get('/pertanyaan/{pertanyaan_id}/edit', 'pertanyaanController@edit');
// Route::put('/pertanyaan/{pertanyaan_id}', 'pertanyaanController@update');
// Route::delete('/pertanyaan/{pertanyaan_id}', 'pertanyaanController@destroy');

//Route::resource('jawaban', 'JawabanController')->shallow();
Route::resource('pertanyaan', 'pertanyaanController')->shallow();

app/Jawaban.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jawaban extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class pertanyaan extends Model
{
    protected $table = "pertanyaan";

    protected $fillable = ['judul','isi','tanggal_dibuat','tanggal_diperbaharui','profil_id'];
    public $timestamps = false;

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/JawabanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class JawabanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/pertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\pertanyaan;

class pertanyaanController extends Controller
{
    function index(){
        //$pertanyaan = DB::table('pertanyaan')->get();

        //eloquent
        $pertanyaan=pertanyaan::all();
        return view('pertanyaan.index', compact('pertanyaan'));
    }

    function create(){

        return view('pertanyaan.create');
    }

    function store(Request $request){
        $request->validate([
            'judul' => 'required|unique:pertanyaan',
            'isi' => 'required',
        ]);

        // $pertanyaan=new pertanyaan();
        // $pertanyaan->timestamps = false;
        // $pertanyaan->judul=$request["judul"];
        // $pertanyaan->isi=$request["isi"];
        // $pertanyaan->tanggal_dibuat=date("Y-m-d");
        // $pertanyaan->tanggal_diperbaharui=date("Y-m-d");
        // $pertanyaan->profil_id=1;
        // $pertanyaan->save();

        // $query = DB::table('pertanyaan')->insert([
        //     "judul" => $request["judul"],
        //     "isi" => $request["isi"],
        //     "tanggal_dibuat" => date("Y-m-d"),
        //     "tanggal_diperbaharui" => date("Y-m-d"),
        //     "profil_id" => 1
        // ]);

        // insert data mass assignment

        $pertanyaan=pertanyaan::create(['judul' => $request["judul"] ,'isi'=>$request["isi"],'tanggal_dibuat'=>date("Y-m-d"),'tanggal_diperbaharui'=>date("Y-m-d"),"profil_id"=>1]);

        return redirect('/pertanyaan');
    }

    function show($pertanyaan_id){
        //$pertanyaan = DB::table('pertanyaan')->where('id', $pertanyaan_id)->first();
        $pertanyaan = pertanyaan::find($pertanyaan_id);

        return view('pertanyaan.show', compact('pertanyaan'));
    }

    function edit($pertanyaan_id){
        $pertanyaan = pertanyaan::find($pertanyaan_id);
        return view('pertanyaan.edit', compact('pertanyaan'));
    }

    function update($pertanyaan_id, Request $request){
        $request->validate([
            'judul' => 'required',
            'isi' => 'required',
        ]);
        //mass update
        pertanyaan::where('id', $pertanyaan_id)
          ->update(['judul' =>  $request["judul"],
                    'isi' =>  $request["isi"],
                    'tanggal_diperbaharui' =>  date("Y-m-d"),
                    ]);


        // $query = DB::table('pertanyaan')
        //     ->where('id',$pertanyaan_id)
        //     ->update([
        //     "judul" => $request["judul"],
        //     "isi" => $request["isi"],
        //     "tanggal_diperbaharui" => date("Y-m-d")
        // ]);
        return redirect('/pertanyaan');
    }

    function destroy($pertanyaan_id){
        //$query = DB::table('pertanyaan')->where('id', $pertanyaan_id)->delete();
        //deleteing an existing model on key

        pertanyaan::destroy($pertanyaan_id);

        return redirect('/pertanyaan');
    }


}

resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Blank Page</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href=" {{asset('/admin_lte/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('/admin_lte/dist/css/adminlte.min.css')}}">
  @stack('css')
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
        @include('adminlte.partial.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
        @include('adminlte.partial.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
        @yield('content')
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

        @include('adminlte.partial.footer')
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script  src="{{asset('admin_lte/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script  src="{{asset('admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script  src="{{asset('admin_lte/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script  src="{{asset('admin_lte/dist/js/demo.js')}}"></script>

@stack('scripts')
</body>
</html>

resources/views/adminlte/partial/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0-rc
    </div>
    <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

resources/views/adminlte/partial/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/data-tables" class="nav-link">Data Tables</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/pertanyaan" class="nav-link">Pertanyaan</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img  src="{{asset('/admin_lte/dist/img/user1-128x128.jpg')}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img  src="{{asset('/admin_lte/dist/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img  src="{{asset('/admin_lte/dist/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/items/create.blade.php
@extends('adminlte.master')

@section('content')
    <h2>ini halaman create </h2>

@endsection


@push('scripts')
<script>
    var items=["items","a"];

    console.log(items);
</script>
@endpush

resources/views/items/index.blade.php
@extends('adminlte.master')

@section('content')
<div class="card">
    <div class="card-header">
        <h3>Halaman Index</h3>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
        <thead>
            <tr>
            <th style="width: 10px">#</th>
            <th>Task</th>
            <th>Progress</th>
            <th style="width: 40px">Label</th>
            </tr>
        </thead>
        <tbody>
            <tr>
            <td>1.</td>
            <td>Update software</td>
            <td>
                <div class="progress progress-xs">
                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                </div>
            </td>
            <td><span class="badge bg-danger">55%</span></td>
            </tr>
            <tr>
            <td>2.</td>
            <td>Clean database</td>
            <td>
                <div class="progress progress-xs">
                <div class="progress-bar bg-warning" style="width: 70%"></div>
                </div>
            </td>
            <td><span class="badge bg-warning">70%</span></td>
            </tr>
            <tr>
            <td>3.</td>
            <td>Cron job running</td>
            <td>
                <div class="progress progress-xs progress-striped active">
                <div class="progress-bar bg-primary" style="width: 30%"></div>
                </div>
            </td>
            <td><span class="badge bg-primary">30%</span></td>
            </tr>
            <tr>
            <td>4.</td>
            <td>Fix and squish bugs</td>
            <td>
                <div class="progress progress-xs progress-striped active">
                <div class="progress-bar bg-success" style="width: 90%"></div>
                </div>
            </td>
            <td><span class="badge bg-success">90%</span></td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/pertanyaan/create.blade.php
@extends('adminlte.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3>Tambah Pertanyaan</h3>
        </div>
        <form action="{{route('pertanyaan.store')}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="judul" id="judul" placeholder="Masukkan Judul">
                @error('judul')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="body">body</label>
                <input type="text" class="form-control" name="isi" id="isi" placeholder="Masukkan Isi">
                @error('isi')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Tambah</button>
        </form>
    </div>
@endsection

@push('scripts')
<script>

</script>
@endpush

resources/views/pertanyaan/edit.blade.php
@extends('adminlte.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3>Edit Pertanyaan</h3>
        </div>
        <form action="{{route('pertanyaan.update',['pertanyaan'=>$pertanyaan->id])}}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="judul" value="{{$pertanyaan->judul}}" id="isi" placeholder="Masukkan Title">
                @error('title')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="body">body</label>
                <input type="text" class="form-control" name="isi"  value="{{$pertanyaan->isi}}"  id="isi" placeholder="Masukkan Body">
                @error('body')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
    </div>
@endsection

@push('scripts')
<script>

</script>
@endpush

resources/views/pertanyaan/index.blade.php
@extends('adminlte.master')

@section('content')
    <div class="card">
        <a href="{{ route('pertanyaan.create')}}" class="btn btn-primary">Tambah</a>
        <table class="table">
            <thead class="thead-light">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Judul</th>
                <th scope="col">Isi</th>
                <th scope="col">Tanggal dibuat</th>
                <th scope="col">Tanggal diperbaharui</th>
                <th scope="col">profil</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
                @forelse ($pertanyaan as $key=>$value)
                    <tr>
                        <td>{{$key + 1}}</th>
                        <td>{{$value->judul}}</td>
                        <td>{{$value->isi}}</td>
                        <td>{{$value->tanggal_dibuat}}</td>
                        <td>{{$value->tanggal_diperbaharui}}</td>
                        <td>{{$value->profil_id}}</td>
                        <td style="display:flex;">
                            <a href="{{route('pertanyaan.show',['pertanyaan'=>$value->id])}}" class="btn btn-info">Show</a>
                            <a href="{{route('pertanyaan.edit',['pertanyaan'=>$value->id])}}" class="btn btn-primary">Edit</a>
                            <form action="{{route('pertanyaan.destroy',['pertanyaan'=>$value->id])}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" class="btn btn-danger my-1" value="Delete">
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr colspan="3">
                        <td>No data</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
@endsection

resources/views/pertanyaan/show.blade.php
@extends('adminlte.master')


@section('content')

    <div class="card">
        <div  class="card-header">
                <h3>Show Post {{$pertanyaan->id}}</h3>
        </div>


    <h4>{{$pertanyaan->judul}}</h4>
    <p>{{$pertanyaan->isi}}</p>


    <br>

    </div>
@endsection